export const IS_LOGIN = 'IS_LOGIN';
export const USER_ROLE = 'USER_ROLE';

export const GET_USERS = 'GET_USERS';
export const GET_POSTS = 'GET_POSTS';
export const GET_COMMENTS = 'GET_COMMENTS';

export const ShowLoading = 'SHOW_LOADING';
export const HideLoading = 'HIDE_LOADING';

export const REGISTER = 'REGISTER';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const UPDATE_USER = 'UPDATE_USER';

export const RESET_SERVICES = 'RESET_SERVICES';
export const GET_SERVICES = 'GET_SERVICES';

export const RESET_PHARMACIES = 'RESET_PHARMACIES';
export const GET_PHARMACIES = 'GET_PHARMACIES';

export const GET_TRANSPORT = 'GET_TRANSPORT';
export const RESET_TRANSPORT = 'RESET_TRANSPORT';

export const GET_LAB_REPORTS = 'GET_LAB_REPORTS';
export const RESET_LAB_REPORTS = 'RESET_LAB_REPORTS';

export const GET_CLINIC = 'GET_CLINIC';
export const RESET_CLINIC = 'RESET_CLINIC';

export const GET_LABORATORY = 'GET_LABORATORY';
export const RESET_LABORATORY = 'RESET_LABORATORY';

export const GET_NURSE = 'GET_NURSE';
export const RESET_NURSE = 'RESET_NURSE';

export const GET_TELE_HEALTH = 'GET_TELE_HEALTH';
export const RESET_TELE_HEALTH = 'RESET_TELE_HEALTH';

export const GET_DOCTOR_RATING = 'GET_DOCTOR_RATING';

export const GET_ALL_USER_RATING = 'GET_ALL_USER_RATING';

export const RESET_CHAT_INDEX = 'RESET_CHAT_INDEX'
export const GET_CHAT_INDEX = 'CHAT_INDEX'

export const GET_PAYMENT_CARD = 'GET_PAYMENT_CARD'
export const UPDATE_DEFAULT_CARD = 'UPDATE_DEFAULT_CARD'
export const DELETE_PAYMENT_CARD = 'DELETE_PAYMENT_CARD'

export const GET_SUB_SERVICES = 'GET_SUB_SERVICES'
export const RESET_SUB_SERVICES = 'RESET_SUB_SERVICES'

export const GET_DOCTOR = 'GET_DOCTOR'
export const RESET_DOCTOR = 'RESET_DOCTOR'

export const GET_FAMILY_MEMBER = 'GET_FAMILY_MEMBER'
export const DELETE_FAMILY_MEMBER = 'DELETE_FAMILY_MEMBER'

export const GET_DOCTOR_APPOINTMENT = 'GET_DOCTOR_APPOINTMENT'
export const RESET_DOCTOR_APPOINTMENT = 'RESET_DOCTOR_APPOINTMENT'
export const LOAD_MORE_DOCTOR_APPOINTMENT = 'LOAD_MORE_DOCTOR_APPOINTMENT'

export const LOAD_MORE_DOCTOR_UPCOMING_APPOINTMENT = 'LOAD_MORE_DOCTOR_UPCOMING_APPOINTMENT'

export const ActionTypes = {

    ChatSession: 'ChatSession',
    ShowLoading: 'SHOW_LOADING',
    HideLoading: 'HIDE_LOADING',
    Get_ChatsIndex: 'Get_ChatsIndex',
    Reset_Get_ChatsIndex: 'Reset_Get_ChatsIndex',
    SEND_ATTACHMENT: 'SEND_ATTACHMENT',

};
export const GET_DOCTOR_PAST_APPOINTMENTS = 'GET_DOCTOR_PAST_APPOINTMENTS';
export const RESET_DOCTOR_PAST_APPOINTMENTS = 'RESET_DOCTOR_PAST_APPOINTMENTS';

export const GET_DOCTOR_UPCOMING_APPOINTMENTS = 'GET_DOCTOR_UPCOMING_APPOINTMENTS';
export const RESET_DOCTOR_UPCOMING_APPOINTMENTS = 'RESET_DOCTOR_UPCOMING_APPOINTMENTS';

export const GET_MEDICAL_ASSISTANT = ' GET_MEDICAL_ASSISTANT';
export const RESET_MEDICAL_ASSISTANT = 'RESET_MEDICAL_ASSISTANT';
